---
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: binding-request
  namespace: service-binding-demo
spec:
  application:
    name: nodejs-rest-http-crud
    group: apps
    version: v1
    resource: deployments
  services:
    - group: postgresql.baiju.dev
      version: v1alpha1
      kind: Database
      name: db-demo
