version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # These projects usually require more manual intervention to bump than
      # usual, so let's ignore them from normal dependabot updates for now.
      - "k8s.io/*"
      - "sigs.k8s.io/*"


  - package-ecosystem: gomod
    directory: "test/_projects/api-client"
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: "test/_projects/api-controller"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "test/acceptance/features/"
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: "hack/check-python/"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "test/acceptance/resources/apps/generic-test-app/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
