---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: service-binding-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: service-binding-operator
  source: redhat-developer-operators
  sourceNamespace: openshift-marketplace
  startingCSV: REPLACE_CSV_VERSION
