apiVersion: v1
kind: Secret
metadata:
  name:  "io.servicebinding.{{ .Release.Name }}"
type: servicebinding.io/mongodb
stringData:
  type: mongodb
  provider: redhat
  host: "{{ .Values.mongodb.sed.hostname }}"
  port: {{ .Values.mongodb.sed.port | quote }}
  username: "{{ .Values.mongodb.sed.username }}"
  password: "{{ .Values.mongodb.sed.password }}"
  database: "{{ .Values.mongodb.sed.databasename }}"