---
# tag::elasticsearch-cluster-role[]
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearch-viewer-role
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups:
      - elasticsearch.k8s.elastic.co
    resources:
      - elasticsearches
    verbs:
      - get
      - list
# end::elasticsearch-cluster-role[]
---
# tag::elasticsearch-deployment[]
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: productsearch-es
  annotations:
    service.binding/type: "elasticsearch"
    service.binding/host: "path={.metadata.name}-es-http.{.metadata.namespace}.svc.cluster.local"
    service.binding/port: "9200"
    service.binding/username: "elastic"
    service.binding/password: "path={.metadata.name}-es-elastic-user,objectType=Secret,sourceKey=elastic"
    service.binding/useSsl: "yes"
spec:
  version: 7.10.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
# end::elasticsearch-deployment[]
