# https://github.com/elastic/helm-charts/blob/7.10.0/elasticsearch/examples/config/values.yaml
clusterName: "elastic-es"
replicas: 1

extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-config-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-config-credentials
        key: username

esConfig:
  elasticsearch.yml: |
    path.data: /usr/share/elasticsearch/data

keystore:
  - secretName: elastic-config-secret
  - secretName: elastic-config-slack
  - secretName: elastic-config-custom-path
    items:
    - key: slack_url
      path: xpack.notification.slack.account.otheraccount.secure_url
