# action.yml
name: 'Collect Kube resources from Kubernetes cluster'
description: 'Collects resources for later debugging from OLM operator testing.'
inputs:
  operator-namespace:
    description: "Operator namespace"
    required: false
    default: ''
  olm-namespace:
    description: "OLM namespace"
    required: false
    default: ''
  test-namespace-file:
    description: "File with test namespace"
    required: false
    default: 'out/test-namespace'
  output-path:
    description: "A path to directory under which to store output files"
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - id: collect-kube-resources
      run: |
        kubectl api-resources --verbs=list --namespaced -o name > resources.namespaced.list
        kubectl api-resources --verbs=list --namespaced=false -o name > resources.cluster-wide.list

        for ns in ${{inputs.operator-namespace}} ${{inputs.olm-namespace}}; do
          OUTPUT=${{inputs.output-path}}/${ns}
          mkdir -p ${OUTPUT}
          for res in $(cat resources.namespaced.list | grep -v secrets); do
            kubectl get ${res} --ignore-not-found -n ${ns} -o yaml > ${OUTPUT}/${res}.yaml;
          done
          mkdir -p $OUTPUT/pod;
          for p in $(kubectl get pods -n ${ns} -o name); do
            for c in $(kubectl get $p -n ${ns} -o jsonpath='{.spec.containers[].name}'); do
              kubectl logs -n ${ns} $p -c $c > $OUTPUT/$p.$c.log;
            done;
          done;
          find ${OUTPUT} -size 0 -delete
        done

        if [ -f ${{ inputs.test-namespace-file }} ]; then
          ns=$(cat ${{ inputs.test-namespace-file }})
          OUTPUT=${{inputs.output-path}}/${ns}
          mkdir -p ${OUTPUT}
          for res in $(cat resources.namespaced.list); do
            kubectl get ${res} --ignore-not-found -n ${ns} -o yaml > ${OUTPUT}/${res}.yaml;
          done
          mkdir -p $OUTPUT/pod;
          for p in $(kubectl get pods -n ${ns} -o name); do
            for c in $(kubectl get $p -n ${ns} -o jsonpath='{.spec.containers[].name}'); do
              kubectl logs -n ${ns} $p -c $c > $OUTPUT/$p.$c.log;
            done;
          done;
          find ${OUTPUT} -size 0 -delete
        fi

        OUTPUT=${{inputs.output-path}}
        for res in $(cat resources.cluster-wide.list); do
          kubectl get ${res} --ignore-not-found -o yaml > ${OUTPUT}/${res}.yaml;
        done
      shell: bash

    - id: collect-operator-logs
      run: |
        mkdir -p ${{inputs.output-path}}
        operator_pod=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.operator-namespace}} | tail -1)
        kubectl logs ${operator_pod} -n ${{inputs.operator-namespace}} > ${{inputs.output-path}}/${operator_pod}.log
      shell: bash
