# action.yml
name: 'Collect Kube resources from Kubernetes cluster'
description: 'Collects resources for later debugging from OLM operator testing.'
inputs:
  operator-namespace:
    description: "Operator namespace"
    required: false
    default: ''
  olm-namespace:
    description: "OLM namespace"
    required: false
    default: ''
  test-namespace-file:
    description: "File with test namespace"
    required: false
    default: 'out/test-namespace'
  output-path:
    description: "A path to directory under which to store output files"
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - id: collect-kube-resources
      run: |
        make collect-kube-resources OPERATOR_NAMESPACE=${{inputs.operator-namespace}} OLM_NAMESPACE=${{inputs.olm-namespace}} TEST_NAMESPACE_FILE=${{inputs.test-namespace-file}} TEST_ACCEPTANCE_RESOURCES_DIR=${{inputs.output-path}}
      shell: bash
