ARG BUILD_DIR=/tmp/github.com/redhat-developer/service-binding-operator

FROM registry.redhat.io/rhel8/go-toolset:1.15 AS builder

USER root

ARG BUILD_DIR

WORKDIR $BUILD_DIR

# TODO: Use a RUN command to copy over specific files/dirs in a different PR
# Collapsing it into a single COPY to reduce layers, as of now.
COPY ${CI_ARCHIVE_SERVICE_BINDING_OPERATOR} .

RUN tar xf ${CI_ARCHIVE_SERVICE_BINDING_OPERATOR} --strip-components=1 && rm ${CI_ARCHIVE_SERVICE_BINDING_OPERATOR}

RUN make build


#--------------------------------------------------------------------

#@follow_tag(ubi8-minimal:8-released)
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4

ARG BUILD_DIR

WORKDIR /
COPY --from=builder $BUILD_DIR/bin/manager .

USER 10001

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="service-binding-operator-container" \
	name="ocp-tools-4-tech-preview/service-binding-rhel8-operator" \
	description="Service Binding Operator" \
	summary="Service Binding Operator" \
	io.openshift.tags="service,binding" \
	maintainer="service-binding-support@redhat.com" \
	version="${CI_CONTAINER_VERSION}" \
    io.k8s.display-name="The Service Binding Operator" \
    io.openshift.build.source-location="${CI_SERVICE_BINDING_OPERATOR_UPSTREAM_URL}" \
    io.openshift.build.commit.url="${CI_SERVICE_BINDING_OPERATOR_UPSTREAM_URL}/commit/${CI_SERVICE_BINDING_OPERATOR_UPSTREAM_COMMIT}" \
    io.openshift.build.commit.id="${CI_SERVICE_BINDING_OPERATOR_UPSTREAM_COMMIT}"
