# permissions for end users to view bindablekinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: clusterworkloadresourcemappings-viewer-role
rules:
- apiGroups:
  - servicebinding.io
  resources:
  - clusterworkloadresourcemappings
  verbs:
  - get
  - list
  - watch
