apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: community-mongodb-view
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups: 
      - mongodbcommunity.mongodb.com
    resources: 
      - mongodbcommunity
      - mongodbcommunity/status
    verbs:
      - get
      - list