apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crunchy-postgres-viewer-role
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - postgresclusters
    verbs:
      - get
      - list
