#!/bin/bash

export WAIT_BEFORE=${WAIT_BEFORE:-120s}
export WAIT_AFTER=${WAIT_AFTER:-300s}
export TEST_PERFORMANCE_USERS_PER_SCENARIO=${TEST_PERFORMANCE_USERS_PER_SCENARIO:-50}
export SKIP_RESOURCE_COUNTS=${SKIP_RESOURCE_COUNTS:-true}
