apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-binding-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - pods/log
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
      - deployments/finalizers
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
      - customresourcedefinitions/status
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - service-binding-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - apps.openshift.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
  - verbs:
      - "*"
    apiGroups:
      - serving.knative.dev
    resources:
      - services
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
