apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebinding-sample
spec:
  type: postgres
  service:
    name: pg-instance
    apiVersion: postgresql.example.dev/v1alpha1
    kind: Database
  workload:
    name: nodejs-rest-http-crud
    apiVersion: apps/v1
    kind: Deployment
