apiVersion: servicebinding.io/v1alpha3
kind: ClusterWorkloadResourceMapping
metadata:
  name: cronjobs.batch
spec:
  versions:
    - version: "*"
      volumes: .spec.jobTemplate.spec.template.spec.volumes
      containers:
        - path: .spec.jobTemplate.spec.template.spec.containers[*]
        - path: .spec.jobTemplate.spec.template.spec.initContainers[*]
