---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: db-operators
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: db-operators
  source: db-operators
  sourceNamespace: openshift-marketplace
  startingCSV: REPLACE_CSV_VERSION
