FROM rhel8/go-toolset:1.13 AS builder

USER root
WORKDIR /tmp

COPY ${CI_ARCHIVE_SERVICE_BINDING_OPERATOR} .

RUN tar xf ${CI_ARCHIVE_SERVICE_BINDING_OPERATOR} --strip-components=1 \
    && rm ${CI_ARCHIVE_SERVICE_BINDING_OPERATOR} \
    && cp -r manifests /.


FROM scratch

COPY --from=builder /manifests /manifests

LABEL com.redhat.component="service-binding-operator-metadata-container" \
	com.redhat.delivery.appregistry="true" \
	name="ocp-tools-43-tech-preview/service-binding-operator-metadata"

