---
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: aws-rds-operator
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: pmacik
