---
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: mydb.to.shell-app
  namespace: service-binding-demo
spec:
  envVarPrefix: "MYDB"
  services:
    - group: aws.pmacik.dev
      version: v1alpha1
      kind: RDSDatabase
      name: mydb
  application:
    name: shell-app
    group: operators.coreos.com
    version: v1
    resource: deploymentconfigs
