---
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: mydb.to.nodejs-app
  namespace: service-binding-demo
spec:
  envVarPrefix: "MYDB"
  services:
    group: aws.pmacik.dev
    version: v1alpha1
    kind: RDSDatabase
    name: mydb
  application:
    name: nodejs-app
    group: apps
    version: v1
    resource: deployments
