on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  security-scan:
    name: Security vulnerability scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract operator image ref
        id: operator-image-ref
        run: |
          export OIR=$(make operator-image-ref)
          echo "operator-image-ref=${OIR}" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@8bd2f9fbda2109502356ff8a6a89da55b1ead252 #master
        with:
          image-ref: ${{ steps.operator-image-ref.outputs.operator-image-ref }}
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5 #v2
        with:
          sarif_file: 'trivy-results.sarif'

  source-scan:
    name: Gosec code scanning
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run gosec
        uses: securego/gosec@a459eb0ba387d9bd083d5c2e2354dbeef2465038 #v2.15.0
        with:
          args: '-no-fail -fmt sarif -out gosec.sarif ./...'

      - name: Upload gosec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5 #v2
        with:
          sarif_file: 'gosec.sarif'